name: aem-2026

channels:

 - conda-forge

dependencies:
 
 # Libreria pre-compilata di GROMACS
 # NB: la versione 2026.x è incompatibile con nglview, quindi non aggionare!
 - gromacs=2025.4=nompi*
 
 # Versione di Python e alcuni moduli di base
 - python==3.11.15
 - numpy==2.3.5
 - scipy==1.17.0
 - pandas==3.0.0
 - matplotlib

 # Moduli per Jupyter notebook
 - notebook=6.5.5
 - ipykernel
 - ipympl

 # Molecular dynamics (visualizzazione)
 - nglview
 - mdanalysis
 
 # Machine learning e postprocessing
 - scikit-image
 - scikit-learn

 # Atomic Simulation Environment (per Neural Network Potentials)
 - ase
